-- 1. 항공사 리스트 테이블
create table public.airlines (
  id bigint generated by default as identity primary key,
  name_kr text not null,
  name_en text not null,
  code text,
  active boolean default true,
  created_at timestamptz default now()
);

-- 초기 항공사 데이터 삽입
insert into public.airlines (name_kr, name_en, code) values
('대한항공', 'Korean Air', 'KE'),
('아시아나 항공', 'Asiana Airlines', 'OZ'),
('제주항공', 'Jeju Air', '7C'),
('루프트한자', 'Lufthansa', 'LH'),
('에어 프랑스', 'Air France', 'AF'),
('KLM 네덜란드 항공', 'KLM', 'KL'),
('영국항공', 'British Airways', 'BA'),
('아메리칸 항공', 'American Airlines', 'AA'),
('델타 항공', 'Delta Air Lines', 'DL'),
('유나이티드 항공', 'United Airlines', 'UA'),
('에미레이트 항공', 'Emirates', 'EK'),
('카타르 항공', 'Qatar Airways', 'QR'),
('싱가포르 항공', 'Singapore Airlines', 'SQ');

-- 2. 발송된 이메일 기록 테이블
create table public.sent_emails (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  calculation_id uuid references public.calculations(id) on delete set null,
  recipient_email text not null,
  subject text not null,
  content text not null,
  sent_at timestamptz default now()
);

-- RLS (보안 정책) 활성화
alter table public.airlines enable row level security;
alter table public.sent_emails enable row level security;

-- 보안 정책 설정
create policy "Airlines are viewable by everyone" on public.airlines for select using (true);
create policy "Users can view own sent emails" on public.sent_emails for select using (auth.uid() = user_id);
create policy "Users can insert own sent emails" on public.sent_emails for insert with check (auth.uid() = user_id);
