-- 1. 댓글 테이블 생성
create table public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint references public.posts(id) on delete cascade not null,
  author_id uuid references public.profiles(id) on delete cascade not null,
  content text not null,
  created_at timestamptz default now()
);

-- RLS 활성화
alter table public.comments enable row level security;

-- 보안 정책 설정
create policy "Comments are viewable by everyone" on public.comments for select using (true);
create policy "Authenticated users can create comments" on public.comments for insert with check (auth.role() = 'authenticated');
create policy "Authors can update own comments" on public.comments for update using (auth.uid() = author_id);
create policy "Authors can delete own comments" on public.comments for delete using (auth.uid() = author_id);
