-- 1. 프로필 테이블 (Auth 연동)
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text,
  avatar_url text,
  email text,
  updated_at timestamptz default now()
);

-- 2. 보상금 계산 결과 저장 테이블
create table public.calculations (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  input_data jsonb not null,
  result_data jsonb not null,
  created_at timestamptz default now()
);

-- 3. 커뮤니티 게시글 테이블
create table public.posts (
  id bigint generated by default as identity primary key,
  author_id uuid references public.profiles(id) on delete cascade,
  title text not null,
  content text,
  tag text,
  airline text,
  route text,
  success boolean default false,
  amt text,
  locale text default 'kr',
  created_at timestamptz default now()
);

-- RLS (보안 정책) 활성화
alter table public.profiles enable row level security;
alter table public.calculations enable row level security;
alter table public.posts enable row level security;

-- 보안 정책 설정
create policy "Public profiles are viewable by everyone" on public.profiles for select using (true);
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);

create policy "Users can view own calculations" on public.calculations for select using (auth.uid() = user_id);
create policy "Users can insert own calculations" on public.calculations for insert with check (auth.uid() = user_id);

create policy "Public posts are viewable by everyone" on public.posts for select using (true);
create policy "Authenticated users can create posts" on public.posts for insert with check (auth.role() = 'authenticated');
create policy "Authors can update own posts" on public.posts for update using (auth.uid() = author_id);

-- 새 사용자 가입 시 프로필 자동 생성 함수 및 트리거
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url, email)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url', new.email);
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
